CREATE DATABASE IF NOT EXISTS blog_rest_api;

USE blog_rest_api;

CREATE TABLE IF NOT EXISTS blogs (id INT(5) NOT NULL AUTO_INCREMENT PRIMARY KEY,title VARCHAR(500) NOT NULL,content VARCHAR(5000) NOT NULL);

INSERT INTO blogs (title, content) VALUES ("Lorem Ipsum Dolor Sit Amet", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent imperdiet dignissim rhoncus. Maecenas non risus malesuada mi volutpat lobortis. Quisque dictum leo vel consectetur dictum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut vestibulum at velit sed cursus. Cras malesuada leo turpis, ac tempus elit aliquet at. Maecenas ex augue, semper tempor turpis vel, sodales commodo lectus. Nunc pulvinar nisl ac nisl luctus malesuada eget et odio.");
INSERT INTO blogs (title, content) VALUES ("Aenean magna purus, fermentum eget maximus ut", "Praesent fringilla, nibh sit amet aliquet ultrices, augue metus vestibulum neque, ac mattis risus felis non urna. Vivamus ut blandit lorem. Suspendisse potenti. Aliquam erat volutpat.");
INSERT INTO blogs (title, content) VALUES ("Pellentesque a imperdiet arcu", "onec dictum est ut purus maximus scelerisque. Pellentesque a imperdiet arcu. Nullam ligula risus, pharetra a laoreet tincidunt, hendrerit non ante. Morbi ante justo, fermentum nec augue ultricies, vestibulum facilisis dui. Phasellus in augue lectus. Quisque ultricies dignissim velit, at sagittis felis consectetur eget.");
INSERT INTO blogs (title, content) VALUES ("Class aptent taciti sociosqu ad litora torquent per conubia", "Phasellus in augue lectus. Quisque ultricies dignissim velit, at sagittis felis consectetur eget. Duis sem lacus, pulvinar sed viverra id, sodales eget massa. Curabitur et purus ipsum. In eu pulvinar nibh. Sed sed pharetra diam. Curabitur sagittis, diam vel semper molestie, neque quam aliquam enim, sed faucibus ante metus quis enim.");
INSERT INTO blogs (title, content) VALUES ("Cras libero enim", "Pellentesque in neque faucibus massa porta ullamcorper. Cras libero enim, tempor eget augue quis, ultricies imperdiet magna. Etiam ut odio urna. Mauris non luctus tellus, et iaculis sem. Sed a turpis sapien.");
INSERT INTO blogs (title, content) VALUES ("Etiam ut odio urna. Mauris non luctus tellus", "Sed dictum a nisi vel consectetur. Donec hendrerit quam id metus vestibulum, eget facilisis lacus consectetur. Vivamus eget lectus congue, volutpat dolor eu, gravida lacus. Donec sit amet tincidunt nisl. Sed rhoncus odio in libero gravida, eu lacinia turpis porttitor. Nam viverra, purus eu accumsan tincidunt, lectus nibh mattis neque, eu rhoncus est ante non felis.");
INSERT INTO blogs (title, content) VALUES ("Maecenas non risus malesuada mi volutpat", "Sed massa tortor, venenatis vitae bibendum eu, cursus ac orci. Aenean magna purus, fermentum eget maximus ut, feugiat at est. Phasellus faucibus lectus sit amet massa viverra, et congue sapien volutpat. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.");